### ISSUE TITLE
 Typos W5-S4 & S5 - fr 

### ISSUE THREAD

**Issue by Fourchaux** [OCamlPro-Henry/ocamlmooc_srt#3]
J'ai envoyé un PR le 17 décembre 2015 dernier sur 'ad0/OcamlMOOC'.
[typos W5 - fr](https://github.com/ad0/OcamlMOOC/pulls)
Ce PR est ,semble-t-il, toujours valable. 
Pouvez-vous le récupérer ou faut-il en créer un autre ici ?

**Comment by OCamlPro-Henry** [comment]
Bonjour, j'ai déjà inclu la PR dans ce dépôt (et dans les sous-titres sur la plate-forme). Pas la peine de refaire une PR, merci !
